#!/bin/bash

# Script for applying patches generated by the cgit CGI web frontend for git
# $1 is the patch generated by cgit

# Here's an example cgit patch from
# https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/patch/?id=3c2993b8c6143d8a5793746a54eba8f86f95240f
# 
# From 3c2993b8c6143d8a5793746a54eba8f86f95240f Mon Sep 17 00:00:00 2001
# From: Linus Torvalds <torvalds@linux-foundation.org>
# Date: Sun, 4 Jun 2017 16:47:43 -0700
# Subject: Linux 4.12-rc4
# 
# ---
#  Makefile | 2 +-
#  1 file changed, 1 insertion(+), 1 deletion(-)
# 
# diff --git a/Makefile b/Makefile
# index 470bd4d..853ae91 100644
# --- a/Makefile
# +++ b/Makefile
# @@ -1,7 +1,7 @@
#  VERSION = 4
#  PATCHLEVEL = 12
#  SUBLEVEL = 0
# -EXTRAVERSION = -rc3
# +EXTRAVERSION = -rc4
#  NAME = Fearless Coyote
#  
#  # *DOCUMENTATION*
# -- 
# cgit v1.1


EDITOR=vim
export EDITOR

DRYRUN=false

PATCH_FILE="$1"

if ! tail -n 2 "$PATCH_FILE" | grep -F "cgit" > /dev/null ; then
  echo "Not a cgit patch!"
  exit 1
fi

SUBJECT_LINE=`sed "4q;d" "$PATCH_FILE"`
# Check that $SUBJECT_LINE starts with "Subject: "
if ! expr "$SUBJECT_LINE" : '\(Subject: \)' > /dev/null ; then
  echo "Can't find the Subject Line"
  exit 1
fi
COMMIT_SUBJECT="${SUBJECT_LINE#Subject: }"
COMMIT_MSG=`sed '/---/q' "$PATCH_FILE" | head -n-1`
COMMIT_MSG=\
"$COMMIT_SUBJECT

$COMMIT_MSG"

echo "Applying Patch..."
if $DRYRUN; then
  # git apply --check "$PATCH_FILE" || exit 1
  patch --dry-run -p1 -i "$PATCH_FILE" || exit 1
else
  # git apply "$PATCH_FILE" || exit 1
  patch -p1 -i "$PATCH_FILE"
  echo "Fix any errors and press enter..."
  read
fi

echo "Checking build..."
./build_kernel.sh
echo "!!! Make sure any newly added files were actually compiled."
echo "Press Enter to Continue..."
read

if ! $DRYRUN; then
  git add -A || exit 1
  git reset apply-cgit-patch.sh
fi

echo "Commiting Patch..."
echo "$COMMIT_MSG" > /tmp/commit_msg.txt
if $DRYRUN; then
  git commit --dry-run -F /tmp/commit_msg.txt -e -v || exit 1
else
  git commit -F /tmp/commit_msg.txt -e -v || exit 1
fi
